architecture: "Unet"

model_params:
  encoder_name: "resnet50"
  encoder_weights: "swsl"
  in_channels: 5
  classes: 11

device: "cuda"
seed: 0
save_path: "./checkpoints/"

training:
  dataloader_params:
    landsat:
      root: "./Megacity2035_MSS/train"
      filename_glob: "**/*.tif"
      exclude: null
    esa:
      root: "./Megacity2035_pseudolabel/train"
      filename_glob: "**/*.tif"
      exclude: null
    sensor_type: "MSS"
    tile_per_loader: 16
    length: 50000
    batch_size: 128
    num_workers: 8

  trainer_params:
    epoch: 100
    gradient_accumulation_factor: null

    loss_fn_params:
      weights: [1.0, 1.0]
      FocalLoss:
        mode: "multiclass"
        alpha: null
        gamma: 2.0
        normalized: False
      TverskyLoss:
        mode: "multiclass"
        alpha: 0.3
        beta: 0.7
        gamma: 2.0

    optimizer_params:
      lr: 5.0e-4
      weight_decay: 1.0e-5

    scheduler_params:
      step_size: 30
      gamma: 0.5
      last_epoch: -1

  validate_params:
    root: "./"
    img_glob: "Megacity2035_MSS/val/**/*.tif"
    gt_glob: "Megacity2035_pseudolabel/val/**/*.tif"

  logger_params:
    PROJECT: "GUC_master"
    NAME: "dummy_landsat1"